//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CgppPhonebook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CgppPhonebook()
        {
            this.CgppDrafts = new HashSet<CgppDraft>();
        }
    
        public int PhoneId { get; set; }
        public Nullable<int> CellNum { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string CellphoneNum { get; set; }
        public string FullName { get; set; }
        public string Position { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> UsersId { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        public virtual CgppDivision CgppDivision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CgppDraft> CgppDrafts { get; set; }
        public virtual CgppGroup CgppGroup { get; set; }
        public virtual CgppOffice CgppOffice { get; set; }
        public virtual User User { get; set; }
    }
}
