//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CgppDraft
    {
        public int Id { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> UsersId { get; set; }
        public Nullable<int> DraftsId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> PhonebooksId { get; set; }
    
        public virtual CgppDivision CgppDivision { get; set; }
        public virtual CgppOffice CgppOffice { get; set; }
        public virtual CgppPhonebook CgppPhonebook { get; set; }
        public virtual Draft Draft { get; set; }
        public virtual User User { get; set; }
    }
}
