//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConcernOffice
    {
        public int concernid { get; set; }
        public Nullable<int> formatid { get; set; }
        public Nullable<int> officeid { get; set; }
        public Nullable<int> isactive { get; set; }
        public Nullable<int> isallAccess { get; set; }
    
        public virtual SMSFormat SMSFormat { get; set; }
    }
}
