//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormattedMessage
    {
        public int smsid { get; set; }
        public Nullable<int> formatid { get; set; }
        public string msg { get; set; }
        public string sender { get; set; }
        public string receiver { get; set; }
        public Nullable<int> isactive { get; set; }
        public Nullable<System.DateTime> date_received { get; set; }
        public Nullable<int> unread { get; set; }
        public Nullable<int> action { get; set; }
        public Nullable<int> broadcast { get; set; }
        public Nullable<int> classid { get; set; }
        public Nullable<int> officeid { get; set; }
    
        public virtual Classification Classification { get; set; }
        public virtual SMSFormat SMSFormat { get; set; }
    }
}
