//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grouping_cellnumbers
    {
        public int id { get; set; }
        public Nullable<int> groupid { get; set; }
        public int pk { get; set; }
        public Nullable<int> systemC { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
