//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_tblSMS_SystemFormat
    {
        public int codeId { get; set; }
        public string sms_format { get; set; }
        public string sms_description { get; set; }
        public string stored_proc_name { get; set; }
        public string stored_proc_param_format { get; set; }
        public Nullable<int> is_with_return { get; set; }
        public string separator { get; set; }
        public Nullable<int> is_active { get; set; }
    }
}
