//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int Pid { get; set; }
        public Nullable<int> Sid { get; set; }
        public Nullable<int> sort { get; set; }
        public string menuname { get; set; }
        public string action { get; set; }
        public string controller { get; set; }
        public string icon { get; set; }
        public Nullable<int> role { get; set; }
    }
}
