//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficialsInformation
    {
        public int offid { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string mname { get; set; }
        public string district { get; set; }
        public string cellno { get; set; }
        public Nullable<int> networkID { get; set; }
        public Nullable<int> OfficialDescID { get; set; }
        public Nullable<int> munid { get; set; }
        public string suffix { get; set; }
        public Nullable<System.DateTime> bday { get; set; }
        public Nullable<int> mynumbers { get; set; }
        public Nullable<int> gender { get; set; }
    
        public virtual Municipality Municipality { get; set; }
        public virtual OfficialsPosition OfficialsPosition { get; set; }
        public virtual PrefixMobileNumber PrefixMobileNumber { get; set; }
    }
}
