//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phonebook
    {
        public int phoneid { get; set; }
        public string cnum { get; set; }
        public string owner_fname { get; set; }
        public string owner_lname { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<System.DateTime> bday { get; set; }
        public string owner_mname { get; set; }
        public string suffix { get; set; }
        public Nullable<int> officeid { get; set; }
        public Nullable<int> eid { get; set; }
        public Nullable<int> isactive { get; set; }
    }
}
