//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pilaKeyword
    {
        public int pilaid { get; set; }
        public string prodcode { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> isactive { get; set; }
        public Nullable<System.DateTime> dateEntered { get; set; }
        public Nullable<int> eid { get; set; }
    }
}
