//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrefixMobileNumber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrefixMobileNumber()
        {
            this.OfficialsInformations = new HashSet<OfficialsInformation>();
        }
    
        public int netsmsID { get; set; }
        public string prefix { get; set; }
        public Nullable<int> networkID { get; set; }
    
        public virtual MobileNetProvider MobileNetProvider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficialsInformation> OfficialsInformations { get; set; }
    }
}
