//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rawMessage
    {
        public int smsid { get; set; }
        public string msg { get; set; }
        public string sender { get; set; }
        public string IMSI { get; set; }
        public Nullable<int> networkID { get; set; }
        public string receiver { get; set; }
        public Nullable<System.DateTime> date_received { get; set; }
    }
}
