//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SentItem
    {
        public int SentItemsID { get; set; }
        public string Destination { get; set; }
        public string message { get; set; }
        public Nullable<int> eid { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public string Systemname { get; set; }
    }
}
