//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimCardInfo
    {
        public int rid { get; set; }
        public string IMSI { get; set; }
        public string ownNumber { get; set; }
        public Nullable<int> networkID { get; set; }
    }
}
