//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsPDU
    {
        public int conid { get; set; }
        public string SmsPdu1 { get; set; }
        public string octet { get; set; }
        public Nullable<int> currentNumber { get; set; }
        public Nullable<int> TotalMessages { get; set; }
        public Nullable<int> ReferenceNumber { get; set; }
    }
}
