//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        public int userid { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string pword { get; set; }
        public string usrname { get; set; }
        public Nullable<int> role { get; set; }
    }
}
