//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStuffNumber
    {
        public int xid { get; set; }
        public string cnums { get; set; }
        public string msg { get; set; }
        public string tag { get; set; }
    }
}
