//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidentifiedNetwork
    {
        public int unidentifiedNoID { get; set; }
        public string cnum { get; set; }
        public string prefix { get; set; }
    }
}
